# Generated by Django 5.0.2 on 2024-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
